### ISSUE TITLE
No module named 'uvicorn.logging'

### ISSUE THREAD

**Issue by simonwanghub** [heyfavour/vue-element-admin-fastapi#10]
/backend/app  python3 app/main.py
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/logging/config.py", line 388, in resolve
    found = getattr(found, frag)
AttributeError: module 'uvicorn' has no attribute 'logging'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/logging/config.py", line 390, in resolve
    self.importer(used)
ModuleNotFoundError: No module named 'uvicorn.logging'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/logging/config.py", line 542, in configure
    formatters[name] = self.configure_formatter(
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/logging/config.py", line 654, in configure_formatter
    result = self.configure_custom(config)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/logging/config.py", line 469, in configure_custom
    c = self.resolve(c)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/logging/config.py", line 397, in resolve
    raise v
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/logging/config.py", line 390, in resolve
    self.importer(used)
ValueError: Cannot resolve 'uvicorn.logging.DefaultFormatter': No module named 'uvicorn.logging'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "app/main.py", line 29, in <module>
    uvicorn.run(app='main:app', host="0.0.0.0", port=8080, log_config=LOGGING_CONFIG)
  File "/Users/abc/Downloads/vue-element-admin-fastapi-master/backend/app/venv/lib/python3.8/site-packages/uvicorn/main.py", line 509, in run
    config = Config(
  File "/Users/abc/Downloads/vue-element-admin-fastapi-master/backend/app/venv/lib/python3.8/site-packages/uvicorn/config.py", line 304, in __init__
    self.configure_logging()
  File "/Users/abc/Downloads/vue-element-admin-fastapi-master/backend/app/venv/lib/python3.8/site-packages/uvicorn/config.py", line 408, in configure_logging
    logging.config.dictConfig(self.log_config)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/logging/config.py", line 808, in dictConfig
    dictConfigClass(config).configure()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/logging/config.py", line 545, in configure
    raise ValueError('Unable to configure '
ValueError: Unable to configure formatter 'default'

**Comment by simonwanghub** [comment]
uvicorn             0.18.1
Python 3.8.2
